// GENERATED by scripts/build.mjs — DO NOT EDIT (source: shared/proxy.ts + platform/)

// shared/proxy.ts
var DEFAULT_TARGET_HOST = "https://opencode.ai";
var HEADER_TARGET = "x-proxy-target";
var ALLOWED_TARGET_HOSTS = ["opencode.ai"];
var REQUEST_TIMEOUT_MS = 6e4;
var VERSION = "2.0.0";
var API_PREFIXES = ["/zen/", "/v1/"];
var CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "*",
  "Access-Control-Max-Age": "86400"
};
function isApiPath(pathname) {
  return API_PREFIXES.some((p) => pathname.startsWith(p));
}
function handlePreflight(request) {
  if (request.method === "OPTIONS") {
    return new Response(null, { headers: CORS_HEADERS });
  }
  if (request.method !== "POST" && request.method !== "GET") {
    return new Response(JSON.stringify({ error: "Only POST and GET allowed" }), {
      status: 405,
      headers: { ...CORS_HEADERS, "Content-Type": "application/json" }
    });
  }
  return null;
}
function jsonResponse(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" }
  });
}
function healthResponse(info) {
  return jsonResponse(200, {
    status: "ok",
    platform: info.platform,
    version: info.version || VERSION,
    noCache: true,
    headers: { "Cache-Control": "no-store" }
  });
}
async function diagnoseResponse(info) {
  const probe = await Promise.race([probeEgress(), delay(4e3)]);
  return jsonResponse(200, {
    platform: info.platform,
    version: info.version || VERSION,
    ipv4: probe ? probe.ipv4 : null,
    ipv6: probe ? probe.ipv6 : null
  });
}
async function probeEgress() {
  const [v4, v6] = await Promise.allSettled([
    fetchOutboundIP("https://api.ipify.org?format=json"),
    fetchOutboundIP("https://api6.ipify.org?format=json")
  ]);
  const ipv4 = v4.status === "fulfilled" ? v4.value : null;
  const ipv6 = v6.status === "fulfilled" ? v6.value : null;
  if (ipv4 == null && ipv6 == null) return null;
  return { ipv4, ipv6 };
}
async function fetchOutboundIP(url) {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3e3);
    try {
      const res = await fetch(url, { signal: controller.signal });
      if (!res.ok) return null;
      const data = await res.json();
      return typeof data.ip === "string" ? data.ip : null;
    } finally {
      clearTimeout(timer);
    }
  } catch {
    return null;
  }
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function resolveProxyTarget(request) {
  const raw = request.headers.get(HEADER_TARGET);
  if (!raw) return null;
  try {
    const url = new URL(raw);
    if (url.protocol !== "https:") return null;
    const host = url.hostname.toLowerCase();
    if (!ALLOWED_TARGET_HOSTS.some((allowed) => host === allowed || host.endsWith("." + allowed))) {
      return null;
    }
    return raw;
  } catch {
    return null;
  }
}
async function proxyToOpenCode(request) {
  const url = new URL(request.url);
  if (!isApiPath(url.pathname)) {
    return jsonResponse(404, { error: "Not found" });
  }
  const target = resolveProxyTarget(request) ?? DEFAULT_TARGET_HOST + url.pathname + url.search;
  const body = request.method === "GET" || request.method === "HEAD" ? void 0 : await request.arrayBuffer();
  const forwardHeaders = new Headers();
  for (const [key, value] of request.headers.entries()) {
    const lowerKey = key.toLowerCase();
    if (lowerKey.startsWith("x-opencode-") || lowerKey === "authorization") {
      forwardHeaders.set(key, value);
    }
  }
  forwardHeaders.set("Content-Type", request.headers.get("Content-Type") || "application/json");
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    return await fetch(target, {
      method: request.method,
      headers: forwardHeaders,
      body,
      signal: controller.signal
    });
  } finally {
    clearTimeout(timer);
  }
}
async function handlePlatformRequest(request, info, pathTransform) {
  const preflight = handlePreflight(request);
  if (preflight) return preflight;
  let path = pathTransform ? pathTransform(new URL(request.url).pathname) : new URL(request.url).pathname;
  if (!path) path = "/";
  if (path === "/health") return healthResponse(info);
  if (path === "/diagnose") return diagnoseResponse(info);
  const targetURL = new URL(request.url);
  if (path !== targetURL.pathname) {
    targetURL.pathname = path;
    const nextRequest = new Request(targetURL.toString(), request);
    return proxyToOpenCode(nextRequest);
  }
  return proxyToOpenCode(request);
}

// platform/netlify.ts
function handler(request) {
  return handlePlatformRequest(request, { platform: "netlify", version: "2.0.0" });
}
export {
  handler as default
};
