// scripts/build.mjs — 平台层单文件产物构建（唯一构建入口）
//
// 单一真源：shared/proxy.ts（转发核心）+ platform/<plat>.ts（入口适配器）
// 产物：各平台部署目录下的单文件脚本（平台侧不做任何 build）
//   Vercel   → api/proxy.js                  (edge, esm, default export)
//   Netlify  → netlify/edge-functions/proxy.js (edge, esm, default export)
//   Deno     → deno/main.js                  (deno runtime, esm, Deno.serve)
//   Supabase → supabase/functions/proxy/index.js (deno runtime, esm, Deno.serve)
//
// 用法：node scripts/build.mjs
// 产物应提交到 git，各平台通过 GitHub Actions 构建后直接部署产物（平台侧不做 build）。

import { build } from "esbuild"
import { mkdirSync } from "node:fs"
import { dirname } from "node:path"

const BANNER = "// GENERATED by scripts/build.mjs — DO NOT EDIT (source: shared/proxy.ts + platform/)"

const targets = [
  {
    entry: "platform/vercel.ts",
    outfile: "api/proxy.js",
    platform: "browser", // Vercel Edge Runtime（V8 isolate，无 Node 全局）
    format: "esm",
    target: "es2022",
  },
  {
    entry: "platform/netlify.ts",
    outfile: "netlify/edge-functions/proxy.js",
    platform: "browser",
    format: "esm",
    target: "es2022",
  },
  {
    entry: "platform/deno.ts",
    outfile: "deno/main.js",
    platform: "neutral", // Deno：不依赖浏览器/Node 全局
    format: "esm",
    target: "es2022",
  },
  {
    entry: "platform/supabase.ts",
    outfile: "supabase/functions/proxy/index.js",
    platform: "neutral",
    format: "esm",
    target: "es2022",
  },
]

let failed = 0

for (const t of targets) {
  try {
    mkdirSync(dirname(t.outfile), { recursive: true })
    const result = await build({
      entryPoints: [t.entry],
      outfile: t.outfile,
      bundle: true,
      minify: true,
      sourcemap: false,
      platform: t.platform,
      format: t.format,
      target: t.target,
      banner: { js: BANNER },
      logLevel: "warning",
    })
    const size = result.metafile
      ? Object.values(result.metafile.outputs)[0]?.bytes ?? 0
      : 0
    console.log(`ok  ${t.outfile}  (${(size / 1024).toFixed(1)} KB)`)
  } catch (err) {
    failed++
    console.error(`✘  ${t.entry} → ${t.outfile}: ${err.message}`)
  }
}

if (failed > 0) {
  console.error(`\n${failed} target(s) failed.`)
  process.exit(1)
}
console.log("\nAll platform artifacts built.")
